name: Update README
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' 

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JasonEtco/readme-box@main
        with:
          filename: README.md
          dynamic-data: |
            <picture>
              <source media="(prefers-color-scheme: dark)" srcset="https://github-readme-activity-graph.vercel.app/graph?username=iLoveRamona&theme=github-dark&hide_border=true&bg_color=0D1117&color=58A6FF&line=1F6FEB&point=388BFD&area=true&area_color=0D419D">
              <source media="(prefers-color-scheme: light)" srcset="https://github-readme-activity-graph.vercel.app/graph?username=iLoveRamona&theme=github-light&hide_border=true&bg_color=FFFFFF&color=0366D6&line=1F6FEB&point=388BFD&area=true&area_color=DBEAFE">
              <img src="https://github-readme-activity-graph.vercel.app/graph?username=iLoveRamona&theme=default&hide_border=true" width="100%">
            </picture>
